# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjetoGuilda' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjetoGuilda

	 pod 'Alamofire'

  target 'ProjetoGuildaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProjetoGuildaUITests' do
    # Pods for testing
  end

end
